version: '3.8'

services:
  web:
    build: .
    ports:
      - "9001:9001"  # Mapeia a porta 9001 do contêiner para a porta 9001 no host
    volumes:
      - .:/app
    depends_on:
      - db
    command: /app/docker-entrypoint.sh

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escola
