from .turma_schema import TurmaSchema
from .materia_schema import MateriaSchema
from .professor_schema import ProfessorSchema
from .turma_materia_schema import TurmaMateriaSchema, TurmaMateriasSchema, MateriaTurmasSchema
from .turma_professor_schema import TurmaProfessorSchema, TurmaProfessoresSchema, ProfessorTurmasSchema
from .professor_materia_schema import ProfessorMateriaSchema, ProfessorMateriasSchema, MateriaProfessoresSchema